### ISSUE TITLE
Undefined Constant

### ISSUE THREAD

**Issue by ciptard** [tovic/bootstrap-shield-for-mecha-cms#1]
Hi,
I found this notice after installing this bootstrap shield : 
`Notice: Use of undefined constant ICON_LIBRARY_PATH - assumed 'ICON_LIBRARY_PATH' in C:\xampp\htdocs\mecha\cabinet\shields\bootstrap\header.php on line 7`

**Comment by taufik-nurrohman** [comment]
@ciptard What **Mecha** version are you using? I was created some [new constant](https://github.com/mecha-cms/cms/blob/v1.1.3-beta.1/index.php#L35) in the `index.php` file since version `1.1.2` (as I remember) to prevent duplicate asset loading in the future. You can remove that constant with the normal **FontAwesome** path to fix the error.
